name: vivu

on:
  # schedule:
  #   - cron: '0 0,6,12,18 * * *'  
    
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-vivu]

# concurrency:
#   group: n8n
#   cancel-in-progress: false
  
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    env:
      TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
      WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
          
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GH_USERNAME }}
          password: ${{ secrets.MAC_GH_TOKEN }} 


      - name: create folder
        run: |
          mkdir -p ~/nginx


      - name: Run docker-compose
        run: |
          docker compose up -d
          
          
      # - name: Free disk space
      #   run: |
      #     # sudo swapoff -a
      #     # sudo apt-get autoremove -y
      #     # sudo apt-get autoclean -y
      #     sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/lib/jvm /usr/share/swift /usr/local/.ghcup /usr/local/julia* /usr/local/share/chromium /opt/microsoft /opt/google /opt/az /usr/local/share/powershell
          

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          all_but_latest: true
          workflow_id: ${{ github.event.workflow.id }}
          access_token: ${{ secrets.GH_TOKEN }}

      - name: Delete old workflow runss
        uses: yanovian/prune-old-actions@v1.0.12
        with:
          token: ${{ secrets.GH_TOKEN }}
          days-ago: 1
          keep-latest: 5

      - name: Do your work
        run: |
          sleep 5.8h
          
          
      - name: Trigger next run
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"deploy-vivu"}'

      - name: Do your work
        run: |
          sleep 1m
